context.objects = [
    {
        factory = spa-device-factory
        args = {
            factory.name = api.alsa.enum.udev
        }
        flags = [ nofail ]
    }
    {
        factory = spa-node-factory
        args = {
            factory.name   = api.alsa.pcm.sink
            node.name      = alsa-sink
            node.description = "ALSA Sink"
            api.alsa.path  = "hw:0"
            api.alsa.period-size = 1024
            audio.format   = S16LE
            audio.rate     = 48000
            audio.channels = 2
        }
        flags = [ nofail ]
    }
]
